services:
  - type: web
    name: coursevia-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        value: https://coursevia-production-5872.up.railway.app
      - key: VITE_SUPABASE_URL
        value: https://lpvcaukviteexnjzqqeo.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwdmNhdWt2aXRlZXhuanpxcWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MTQxNDgsImV4cCI6MjA4OTQ5MDE0OH0.rHd16T2wKEUxyu2IWME-faqW-ZlrW8fNCmFaTs1IiV8
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        value: pk_live_51SzYAsDrKgcLcR6egdhVeVl8nSVqpQQBwE5dYpcCo3Zl1VzFqiAotYV6ywZqIwqvF7702bRGkpDrcFDfpr9yh34z00pKMs7hvf
      - key: VITE_CHECKOUT_PUBLIC_KEY
        value: pk_sbox_n3b2guhpa4gbnln2di5xytqztme
      - key: VITE_SITE_SEARCH_360_ID
        value: "57286"
      - key: VITE_SITE_SEARCH_360_API_KEY
        value: 0tg7ii7k2u602t74yws909v24s3j7763
